version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      # Adicione outras variáveis de ambiente conforme necessário
    depends_on:
      - postgresql
    volumes:
      - './custom-themes:/opt/bitnami/keycloak/themes'
      # Adicione outros volumes conforme necessário

volumes:
  postgresql_data:
    driver: local
